name: Test

on:
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: test env
      run: |
        curl \
        --url https://api.github.com/repos/arai-a/ecma262-compare/branches/gh-pages \
        --header 'content-type: application/json' | \
        python -c 'import sys; import json; print("##[set-output name=sha;]{}".format(json.loads(sys.stdin.read())["commit"]["sha"]))'
      id: foo
    - name: echo
      run: |
        echo "sha is"
        echo ${{steps.foo.outputs.sha}}
