name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test comment
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/8dac63919644fa8217ab2423f1a7cb87c52182ff \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{ "state": "success", "target_url": "https://arai-a.github.io/ecma262-compare/", "context": "ecma262-compare", "description": "compare PR" }'
